In [11]:
import pandas as pd
import numpy as np
import math
from pandas_profiling import ProfileReport
from sklearn.linear_model import LinearRegression
from word2number import w2n

In [10]:
file = pd.read_csv("/Users/yudiudyan/Desktop/iNeuron/Code Basics - Entire GitHub Clone/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
file

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

###### Data Pre-Processing for the columns is as follows:

1. For 'experience':

    a. we will fill all the missing values using fillna function (put zero for all the null values) 
    
    b. Use the word2number library to convert the text to numbers.
    

2. for 'test_score(out of 10)', we will use the median to fill the missing value.

In [12]:
file.experience = file.experience.fillna("zero")
file.experience = file.experience.apply(w2n.word_to_num)
file

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [14]:
median_test_score = math.floor(file['test_score(out of 10)'].mean())
file['test_score(out of 10)'] = file['test_score(out of 10)'].fillna(median_test_score)
file

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [25]:
# making features and columns
x = file.drop(columns=['salary($)'])
y = file['salary($)']
# the feature column
x

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    7.0                           7
7          11                    7.0                           8

In [26]:
# the label column:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

#### Building the Model:

In [20]:
lin_reg = LinearRegression()
lin_reg.fit(x,y)

LinearRegression()

In [24]:
print(lin_reg.coef_,"\n")
print(lin_reg.intercept_)

[2922.26901502 2221.30909959 2147.48256637] 

14992.65144669314


In [29]:
# predicting the values for 2, 9, 6:
lin_reg.predict([[2,9,6]])

array([53713.86677124])

In [30]:
# predicting the values for 12, 10, 10:
lin_reg.predict([[12,10,10]])

array([93747.79628651])